### ISSUE TITLE
User部分API GET parameters 格式錯誤

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#20]
`/user/scores`
​`/user​/coursetable`
`/user/reward-and-penalty`
`/user​/midterm-alerts`

文件中parameters是year,semester
實作成year,value 需要更改

**Comment by abc873693** [comment]
是文件需要更改
還是API需要更改？

**Comment by takidog** [comment]
@abc873693 
API更改為year, semester

**Comment by takidog** [comment]
#22
