### ISSUE TITLE
請假功能 流程問題

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#42]
#### 導師選擇問題
move #43 .

---
## 流程問題
這邊提出一個想法

使用者發送請假資訊&請假證明  >> API接收，檢查欄位是否正確後，**立即**返回一組task id(隨機)   >> (後端再慢慢的幫他送請假)

1. 使用者可以透過task id 查詢到目前後端處理的進度 (開一個新的API)
成功失敗都顯示
2. 使用者可以查詢自己所有的請假進度(後端的請假進度)   (也是開一個新的API)
(或是以上2個擇一，我比較傾向使用第2點)

後端請假紀錄保存24h
後續要查詢請假紀錄，如果是成功的，應該會在假單查詢看到(學校架單)

---
跨日請假， 請的節數越多，花費的時間就越久
可能需要這樣來減少使用者等待的時間

~什麼爛請假系統，最難爬的網站沒有之一~

**Comment by takidog** [comment]
@abc873693 
麻煩了

**Comment by abc873693** [comment]
簡單來說 這個 `請假進度` 
單純是為了加速 向校務系統送出請求 這個過程
而學校系統的請假進度不含在此？

**Comment by abc873693** [comment]
另外導師選擇問題及請假流程應該分別開兩個issue 
這個issue單純討論 請假流程 即可

**Comment by takidog** [comment]
> 簡單來說 這個 `請假進度`
> 單純是為了加速 向校務系統送出請求 這個過程
> 而學校系統的請假進度不含在此？

是，學校的請假進度 應該要再假單查詢去處理(可以查詢)
應該算是加速使用者拿到回傳的時間

**Comment by abc873693** [comment]
> > 簡單來說 這個 `請假進度`
> > 單純是為了加速 向校務系統送出請求 這個過程
> > 而學校系統的請假進度不含在此？
> 
> 是，學校的請假進度 應該要再假單查詢去處理(可以查詢)
> 應該算是加速使用者拿到回傳的時間

有測試過請假節數對應所需要的時間的對應表嗎？
如果這塊沒描述清楚，我覺得可能使用的人會很困惑

**Comment by takidog** [comment]
> > > 簡單來說 這個 `請假進度`
> > > 單純是為了加速 向校務系統送出請求 這個過程
> > > 而學校系統的請假進度不含在此？
> > 
> > 
> > 是，學校的請假進度 應該要再假單查詢去處理(可以查詢)
> > 應該算是加速使用者拿到回傳的時間
> 
> 有測試過請假節數對應所需要的時間的對應表嗎？
> 如果這塊沒描述清楚，我覺得可能使用的人會很困惑

我這邊沒有一個全部流程的測試結果，下面有標時間的，在剛剛測試時有紀錄

學校的請假系統，按下去的任何按鈕都是一個post，**且要照順序來**
(選擇請假別(1 post) + 10節課(10 post) + 下一步(1post) + 證明(upload file ) + 提交(1 post)  )  
前面login也要包含 (**2s** 不穩定)

剛剛在離峰時段，我這邊測得單一個封包50~100ms() 
Python還有要處理

請假證明還沒嘗試過提交，這裡有牽扯到上傳檔案會有更多的延遲在

**Comment by abc873693** [comment]
> > > > 簡單來說 這個 `請假進度`
> > > > 單純是為了加速 向校務系統送出請求 這個過程
> > > > 而學校系統的請假進度不含在此？
> > > 
> > > 
> > > 是，學校的請假進度 應該要再假單查詢去處理(可以查詢)
> > > 應該算是加速使用者拿到回傳的時間
> > 
> > 
> > 有測試過請假節數對應所需要的時間的對應表嗎？
> > 如果這塊沒描述清楚，我覺得可能使用的人會很困惑
> 
> 我這邊沒有一個全部流程的測試結果，下面有標時間的，在剛剛測試時有紀錄
> 
> 學校的請假系統，按下去的任何按鈕都是一個post，**且要照順序來**
> (選擇時間範圍(1 post) + 選擇請假別(1 post) + 10節課(10 post) + 下一步(1post) + 證明(upload file ) + 提交(1 post) )
> 前面login也要包含 (**2s** 不穩定)
> 
> 剛剛在離峰時段，我這邊測得單一個封包50~100ms (選一節課的假)
> Python還有要處理
> 
> 請假證明還沒嘗試過提交，這裡有牽扯到上傳檔案會有更多的延遲在

後來想了一下
理論上會把請假過程分成兩階段性(API上傳及學校流程)
這會造成使用者萬一前者沒成功又要重來一次
會造成體驗不佳
我認為應該是讓使用者當下就能確認是否有上傳成功
上傳速度不佳 這部分若是有這狀況
另開issue討論
