### ISSUE TITLE
請假功能 導師選擇問題

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#43]
## 導師選擇問題
第一個問在discord上有提，研究生/沒有預設導師的學生，會需要手動去選擇導師，
[gist json](https://gist.github.com/takidog/d692a8f90a5e5c611e49d4511f6be968)
並且在`/leaves/submit/info` 添加欄位，讓前端可以得知使用者需不需要手動選擇導師．

**Comment by takidog** [comment]
搬移已經討論且同意
`/leaves/submit/info`
`tutors `欄位中 新增 `tutorId`

刪除 `teacherList `

如果
```json
{
"tutors":{
"name":null,
"tutorId":null
}
}
```
代表使用者需要透過手動選擇

**Comment by takidog** [comment]
@abc873693 
現在行事曆是放firebase嗎 
我覺得 導師列表 應該也放那

要自動生成的成本太高(耗時)
ㄧ學期一更應可以滿足大部分需求

如果要放在API，勢必要有另一個Python 排程去跑
請假系統是沒有訪客帳號的，我們要有帳號固定在主機上

**Comment by abc873693** [comment]
> @abc873693
> 現在行事曆是放firebase嗎
> 我覺得 導師列表 應該也放那
> 
> 要自動生成的成本太高(耗時)
> ㄧ學期一更應可以滿足大部分需求
> 
> 如果要放在API，勢必要有另一個Python 排程去跑
> 請假系統是沒有訪客帳號的，我們要有帳號固定在主機上

我認為可以，但需要有另外的issue來描述這個問題
但放在firebase或是存在一個地方需要評估，
也有一個問題是如果單純使用這個api，他仍然需要一個管道取得這些資訊，
本專案目的不在於專注配合app功能

**Comment by takidog** [comment]
> > @abc873693
> > 現在行事曆是放firebase嗎
> > 我覺得 導師列表 應該也放那
> > 要自動生成的成本太高(耗時)
> > ㄧ學期一更應可以滿足大部分需求
> > 如果要放在API，勢必要有另一個Python 排程去跑
> > 請假系統是沒有訪客帳號的，我們要有帳號固定在主機上
> 
> 我認為可以，但需要有另外的issue來描述這個問題
> 但放在firebase或是存在一個地方需要評估，
> 也有一個問題是如果單純使用這個api，他仍然需要一個管道取得這些資訊，
> 本專案目的不在於專注配合app功能

後續我會把生成json的工具放出來
會特別在README.md說明需要產生這份資料

**Comment by abc873693** [comment]
> > > @abc873693
> > > 現在行事曆是放firebase嗎
> > > 我覺得 導師列表 應該也放那
> > > 要自動生成的成本太高(耗時)
> > > ㄧ學期一更應可以滿足大部分需求
> > > 如果要放在API，勢必要有另一個Python 排程去跑
> > > 請假系統是沒有訪客帳號的，我們要有帳號固定在主機上
> > 
> > 
> > 我認為可以，但需要有另外的issue來描述這個問題
> > 但放在firebase或是存在一個地方需要評估，
> > 也有一個問題是如果單純使用這個api，他仍然需要一個管道取得這些資訊，
> > 本專案目的不在於專注配合app功能
> 
> 後續我會把生成json的工具放出來
> 會特別在README.md說明需要產生這份資料

可以
文件頁面最好也一份

**Comment by abc873693** [comment]
#46
