### ISSUE TITLE
請假功能  /leave/submit/info 畢業生回傳問題

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#48]
文件上有標403 `User can't user this feature`

當初沒有實作出來

有需要修改其他回傳值嗎

**Comment by abc873693** [comment]
理論上不用
但我一直覺得類似這種是不是要有一定格式
message 和 error code
用json表示

**Comment by takidog** [comment]
> 理論上不用
> 但我一直覺得類似這種是不是要有一定格式
> message 和 error code
> 用json表示

目前看起來，沒有其他狀態會跟這個一個api上的403衝突
應該可以先只回應403

**Comment by takidog** [comment]
以防萬一
還是定義一下
http status code : 403
```json 
{
    "code":400
}
```

這樣可以嗎?
@abc873693

**Comment by abc873693** [comment]
tile 改 message比較妥

**Comment by takidog** [comment]
> tile 改 message比較妥

那個是falcon預設的回應方式
還是要另外用一個有message的?

**Comment by abc873693** [comment]
其他api 也是這樣？

**Comment by takidog** [comment]
是
除了200 其他的錯誤都是用falcon內建的回應
有多種錯誤狀態的也是用這

**Comment by abc873693** [comment]
> > tile 改 message比較妥
> 
> 那個是falcon預設的回應方式
> 還是要另外用一個有message的?
> 
> 也可以預設的回應調整成這樣
> 
> ```json
> {
>     "title": "403 Forbidden",
>     "description": "400, graduate can't use this feature ",
>     "code": 400
> }
> ```

這樣這個OK

**Comment by abc873693** [comment]
#50
