### ISSUE TITLE
修正 leaves 字眼至 leave

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#51]
文件初是只有查詢請假單，leaves  指複數資料

目前 leave 下擁有較多功能，Python上是採用學校的命名方法 `leave`

統一 api route 
將 
`/leaves`  >>  `/leave/all`
`/leaves/submit` >> `/leave/submit`
`/leaves/submit/info` >> `/leave/submit/info`

**Comment by abc873693** [comment]
除此之外 api相關請求的變數 需要重新命名
