### ISSUE TITLE
最新消息 額外的管理員登入方式

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#62]
目前最新消息的管理員驗證，是透過校務系統登入後
判斷JWT裡的username是否為管理員的帳號

在校務系統維護時，會有沒有辦法管理最新消息的問題

1. 在環境變數中，輸入管理員帳號密碼
透過`/oauth/token`做判斷
(可以在falcon JWT middleware 就判斷並返回)

2. 在環境變數中，輸入管理員帳號密碼
額外開設一組管理員的登入API 來發 JWT
像是 `/oauth/admin/token` 
(可以在討論)

**Comment by abc873693** [comment]
#64 Fixed
