### ISSUE TITLE
最新消息 過期時間 在現在時間之前 計算錯誤

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#66]
如題

需要回應過期時間

目前時間計算遇到負數會出現問題
一併修正

**Comment by abc873693** [comment]
描述無法看懂發生什麼事情
遇到負數會出現什麼問題？
如題本身並無表示發生什麼事情

**Comment by takidog** [comment]
`datetime`計算時間差 使用`.seconds` 只會得到中間相差的時間
並沒有負數的形況

導致時間往上加

假設:10:00 新增一份  9:00過期的最新消息
實際上會到11:00才過期

**Comment by takidog** [comment]
#68 
#69
