### ISSUE TITLE
學期成績查詢「總平均、班名次百分比」異常處理

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#78]
目前學校webap 已經移除班名次百分比了
可能要換成前後端計算或是移除這個欄位

查看log後有發現爬蟲在爬總平均時部分會報錯
異常處理需要補上

**Comment by abc873693** [comment]
我建議是後端補，維持舊版有使用的這個API的人員

**Comment by takidog** [comment]
> 我建議是後端補，維持舊版有使用的這個API的人員

好

**Comment by takidog** [comment]
#99
