### ISSUE TITLE
學期成績新增系排欄位

### ISSUE THREAD

**Issue by abc873693** [NKUST-ITC/NKUST-AP-API#94]
現行學校有支援查詢系排名
API /user/scores
新增欄位 `departmentRank`
API格式
```json
{
   "detail": {
       "conduct": 82,
       "average": 39,
       "classRank": "57/57",
       "departmentRank":"12/123",
       "classPercentage": 100
    }
}
```

**Comment by takidog** [comment]
需要移除 `classPercentage `
學校不提供了

**Comment by abc873693** [comment]
> 需要移除 `classPercentage `
> 學校不提供了

是可以移除  
也可以考慮由後端計算  
若要移除前端我需要確認會不會炸到舊版

**Comment by takidog** [comment]
> > 需要移除 `classPercentage `
> > 學校不提供了
> 
> 是可以移除
> 也可以考慮由後端計算
> 若要移除前端我需要確認會不會炸到舊版

我開在feature
可以之後版本一起強制更新(?

**Comment by abc873693** [comment]
目前版本的比例  
3.3.7是強制更新版本所以會預期的高  
我想應該不會是太大的問題
![](https://i.imgur.com/YUk0ojG.png)

**Comment by abc873693** [comment]
> > > 需要移除 `classPercentage `
> > > 學校不提供了
> > 
> > 
> > 是可以移除
> > 也可以考慮由後端計算
> > 若要移除前端我需要確認會不會炸到舊版
> 
> 我開在feature
> 可以之後版本一起強制更新(?

確認沒啥問題 可以直接改

**Comment by takidog** [comment]
> > > > 需要移除 `classPercentage `
> > > > 學校不提供了
> > > 
> > > 
> > > 是可以移除
> > > 也可以考慮由後端計算
> > > 若要移除前端我需要確認會不會炸到舊版
> > 
> > 
> > 我開在feature
> > 可以之後版本一起強制更新(?
> 
> 確認沒啥問題 可以直接改

目前commit已經改上去了
送個文件就提pr

**Comment by takidog** [comment]
#99
