### ISSUE TITLE
更好的校車時刻表

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/NKUST-AP-API#95]
在獲取單天時刻表，需要約1s上下的延遲

一般的時刻表，上面會有`這個user預約狀態`
講白了就是一份`普通的時刻表`跟`自己預定的表單`的融合

但在獲取自己的校車預約表單只需要 100~200ms

可以做到
全部學生共用一份時刻表 並且延長cache過期時間
(過期時間可以設定為那一天時刻表+1 day)
在單獨載入 自己預定的表單做合併

可以讓第一次讀入的時間加快許多

~~至於 校車過了預約時間
可以利用json檢查，去算時間並且阻擋預約~~

**Comment by abc873693** [comment]
> 在獲取單天時刻表，需要約1s上下的延遲
> 
> 一般的時刻表，上面會有`這個user預約狀態`
> 講白了就是一份`普通的時刻表`跟`自己預定的表單`的融合
> 
> 但在獲取自己的校車預約表單只需要 100~200ms
> 
> 可以做到
> 全部學生共用一份時刻表 並且延長cache過期時間
> (過期時間可以設定為那一天時刻表+1 day)
> 在單獨載入 自己預定的表單做合併
> 
> 可以讓第一次讀入的時間加快許多
> 
> 至於 校車過了預約時間
> 可以利用json檢查，去算時間並且阻擋預約

沒啥問題  
就是要相容舊版的格式就沒問題

**Comment by takidog** [comment]
`feature/#95`
時刻表跟舊版相容

~~之前寫什麼爛邏輯~~

**Comment by takidog** [comment]
#98
